name: Build & Release

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'  # ou a versão que preferir

      - name: Build for Linux (ELF)
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/wattpad-to-ebook-x64

      - name: Build for Windows (EXE)
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/wattpad-to-ebook-x64.exe

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/wattpad-to-ebook-x64
            dist/wattpad-to-ebook-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
