name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/wattpad-to-ebook-x64.exe
          GOOS=linux GOARCH=amd64 go build -o dist/wattpad-to-ebook-linux-x64

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/wattpad-to-ebook-x64.exe
            dist/wattpad-to-ebook-linux-x64
